name: Build and Test Python App

on:
  push:
    branches: [ "*" ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          if [ -f test-requirements.txt ]; then pip install -r test-requirements.txt; fi

      - name: Run tests
        run: |
          pytest tests/
